%% 02_make_model.m
% Programmatically create ACC MILS model and link dictionary.

thisFile = mfilename('fullpath');
if isempty(thisFile)
    st = dbstack('-completenames');
    thisFile = st(1).file;
end
repoRoot = fileparts(fileparts(thisFile));
modelName = 'acc_mils';
modelPath = fullfile(repoRoot, 'model', [modelName '.slx']);
dictPath = fullfile(repoRoot, 'data', 'acc_params.sldd');

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist(modelPath, 'file')
    delete(modelPath);
end

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'DataDictionary', dictPath, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'dt', ...
    'StopTime', 'StopTime');

% Input block (robust for SimulationInput.setVariable)
add_block('simulink/Sources/From Workspace', [modelName '/vL_FromWs'], ...
    'Position', [40 80 190 110], ...
    'VariableName', 'vL_ts', ...
    'SampleTime', '-1', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

% Core blocks
add_block('simulink/Discrete/Unit Delay', [modelName '/vE_z1'], ...
    'Position', [220 40 280 70], 'SampleTime', 'dt', 'InitialCondition', 'vE0');
add_block('simulink/Discrete/Unit Delay', [modelName '/d_z1'], ...
    'Position', [220 110 280 140], 'SampleTime', 'dt', 'InitialCondition', 'd_init');
add_block('simulink/Discrete/Unit Delay', [modelName '/mode_z1'], ...
    'Position', [220 180 280 210], 'SampleTime', 'dt', 'InitialCondition', '0', 'OutDataTypeStr', 'uint8');
add_block('simulink/Discrete/Unit Delay', [modelName '/aPrev_z1'], ...
    'Position', [220 250 280 280], 'SampleTime', 'dt', 'InitialCondition', '0');

add_block('simulink/User-Defined Functions/MATLAB Function', [modelName '/ACC_Controller'], ...
    'Position', [460 140 710 300]);
add_block('simulink/User-Defined Functions/MATLAB Function', [modelName '/Plant_Update'], ...
    'Position', [820 70 1030 170]);

% Parameter constant blocks
pNames = {'dt','vSet','Th','d0','Kv_free','Kd','Kv_rel','aMin','aMax','jMax','dDetectOn','dDetectOff','dEmergency'};
for i = 1:numel(pNames)
    y = 330 + 35*(i-1);
    add_block('simulink/Sources/Constant', [modelName '/' pNames{i}], ...
        'Position', [50 y 160 y+20], 'Value', pNames{i});
end

% Logging blocks
add_block('simulink/Sinks/To Workspace', [modelName '/ToWs_vE'], ...
    'Position', [1120 40 1230 70], 'VariableName', 'vE_log', 'SaveFormat', 'Structure With Time');
add_block('simulink/Sinks/To Workspace', [modelName '/ToWs_d'], ...
    'Position', [1120 90 1230 120], 'VariableName', 'd_log', 'SaveFormat', 'Structure With Time');
add_block('simulink/Sinks/To Workspace', [modelName '/ToWs_aCmd'], ...
    'Position', [760 250 880 280], 'VariableName', 'aCmd_log', 'SaveFormat', 'Structure With Time');

% Controller code
ctrlCode = [ ...
"function [aCmd, mode] = fcn(vE, d, vL, modePrev, aPrev, dt, vSet, Th, d0, Kv_free, Kd, Kv_rel, aMin, aMax, jMax, dDetectOn, dDetectOff, dEmergency)" newline ...
"%#codegen" newline ...
"mode = modePrev;" newline ...
"if modePrev == uint8(0)" newline ...
"    if d < dDetectOn" newline ...
"        mode = uint8(1);" newline ...
"    end" newline ...
"else" newline ...
"    if d > dDetectOff" newline ...
"        mode = uint8(0);" newline ...
"    end" newline ...
"end" newline ...
"if d < dEmergency" newline ...
"    aRaw = aMin;" newline ...
"else" newline ...
"    if mode == uint8(0)" newline ...
"        aRaw = Kv_free * (vSet - vE);" newline ...
"    else" newline ...
"        dRef = d0 + Th * vE;" newline ...
"        aRaw = Kd * (d - dRef) + Kv_rel * (vL - vE);" newline ...
"    end" newline ...
"end" newline ...
"if aRaw > aMax" newline ...
"    aSat = aMax;" newline ...
"elseif aRaw < aMin" newline ...
"    aSat = aMin;" newline ...
"else" newline ...
"    aSat = aRaw;" newline ...
"end" newline ...
"aHi = aPrev + jMax * dt;" newline ...
"aLo = aPrev - jMax * dt;" newline ...
"if aSat > aHi" newline ...
"    aCmd = aHi;" newline ...
"elseif aSat < aLo" newline ...
"    aCmd = aLo;" newline ...
"else" newline ...
"    aCmd = aSat;" newline ...
"end" newline ...
"if aCmd > aMax" newline ...
"    aCmd = aMax;" newline ...
"elseif aCmd < aMin" newline ...
"    aCmd = aMin;" newline ...
"end" newline ...
];
set_param([modelName '/ACC_Controller'], 'Script', ctrlCode);

plantCode = [ ...
"function [vE_next, d_next] = fcn(vE, d, vL, aCmd, dt)" newline ...
"%#codegen" newline ...
"vE_next = vE + aCmd * dt;" newline ...
"if vE_next < 0" newline ...
"    vE_next = 0;" newline ...
"end" newline ...
"d_next = d + (vL - vE) * dt;" newline ...
"if d_next < 0" newline ...
"    d_next = 0;" newline ...
"end" newline ...
];
set_param([modelName '/Plant_Update'], 'Script', plantCode);

% Wiring
add_line(modelName, 'vE_z1/1', 'ACC_Controller/1');
add_line(modelName, 'd_z1/1', 'ACC_Controller/2');
add_line(modelName, 'vL_FromWs/1', 'ACC_Controller/3');
add_line(modelName, 'mode_z1/1', 'ACC_Controller/4');
add_line(modelName, 'aPrev_z1/1', 'ACC_Controller/5');

for i = 1:numel(pNames)
    add_line(modelName, [pNames{i} '/1'], ['ACC_Controller/' num2str(i+5)]);
end

add_line(modelName, 'vE_z1/1', 'Plant_Update/1');
add_line(modelName, 'd_z1/1', 'Plant_Update/2');
add_line(modelName, 'vL_FromWs/1', 'Plant_Update/3');
add_line(modelName, 'ACC_Controller/1', 'Plant_Update/4');
add_line(modelName, 'dt/1', 'Plant_Update/5');

add_line(modelName, 'Plant_Update/1', 'vE_z1/1', 'autorouting', 'on');
add_line(modelName, 'Plant_Update/2', 'd_z1/1', 'autorouting', 'on');
add_line(modelName, 'ACC_Controller/2', 'mode_z1/1');
add_line(modelName, 'ACC_Controller/1', 'aPrev_z1/1');

add_line(modelName, 'vE_z1/1', 'ToWs_vE/1');
add_line(modelName, 'd_z1/1', 'ToWs_d/1');
add_line(modelName, 'ACC_Controller/1', 'ToWs_aCmd/1');

save_system(modelName, modelPath);
close_system(modelName);

fprintf('[02_make_model] created: %s\n', modelPath);
