%% make_model_02.m
% Programmatically create ACC MILS model and link dictionary.

thisFile = mfilename('fullpath');
if isempty(thisFile)
    st = dbstack('-completenames');
    thisFile = st(1).file;
end
repoRoot = fileparts(fileparts(thisFile));
modelName = 'acc_mils';
modelPath = fullfile(repoRoot, 'model', [modelName '.slx']);
dictPath = fullfile(repoRoot, 'data', 'acc_params.sldd');

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist(modelPath, 'file')
    delete(modelPath);
end

new_system(modelName);
open_system(modelName);

% Link data dictionary with compatibility fallback for older MATLAB versions.
[~, dictFile, dictExt] = fileparts(dictPath);
dictNameOnly = [dictFile dictExt];
try
    set_param(modelName, 'DataDictionary', dictPath);
catch
    % Some versions reject full paths and accept only dictionary filename on path.
    set_param(modelName, 'DataDictionary', dictNameOnly);
end

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'dt', ...
    'StopTime', 'StopTime');

% Input block (robust for SimulationInput.setVariable)
add_block('simulink/Sources/From Workspace', [modelName '/vL_FromWs'], ...
    'Position', [40 80 190 110], ...
    'VariableName', 'vL_ts', ...
    'SampleTime', '-1', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

% Core blocks
add_block('simulink/Discrete/Unit Delay', [modelName '/vE_z1'], ...
    'Position', [220 40 280 70], 'SampleTime', 'dt', 'InitialCondition', 'vE0');
add_block('simulink/Discrete/Unit Delay', [modelName '/d_z1'], ...
    'Position', [220 110 280 140], 'SampleTime', 'dt', 'InitialCondition', 'd_init');
add_block('simulink/Discrete/Unit Delay', [modelName '/mode_z1'], ...
    'Position', [220 180 280 210], 'SampleTime', 'dt', 'InitialCondition', '0', 'OutDataTypeStr', 'uint8');
add_block('simulink/Discrete/Unit Delay', [modelName '/aPrev_z1'], ...
    'Position', [220 250 280 280], 'SampleTime', 'dt', 'InitialCondition', '0');

add_block('simulink/User-Defined Functions/MATLAB Function', [modelName '/ACC_Controller'], ...
    'Position', [460 140 710 300]);
add_block('simulink/User-Defined Functions/MATLAB Function', [modelName '/Plant_Update'], ...
    'Position', [820 70 1030 170]);

% Parameter constant blocks
pNames = {'dt','vSet','Th','d0','Kv_free','Kd','Kv_rel','aMin','aMax','jMax','dDetectOn','dDetectOff','dEmergency'};
for i = 1:numel(pNames)
    y = 330 + 35*(i-1);
    add_block('simulink/Sources/Constant', [modelName '/' pNames{i}], ...
        'Position', [50 y 160 y+20], 'Value', pNames{i});
end

% Logging blocks
add_block('simulink/Sinks/To Workspace', [modelName '/ToWs_vE'], ...
    'Position', [1120 40 1230 70], 'VariableName', 'vE_log', 'SaveFormat', 'Structure With Time');
add_block('simulink/Sinks/To Workspace', [modelName '/ToWs_d'], ...
    'Position', [1120 90 1230 120], 'VariableName', 'd_log', 'SaveFormat', 'Structure With Time');
add_block('simulink/Sinks/To Workspace', [modelName '/ToWs_aCmd'], ...
    'Position', [760 250 880 280], 'VariableName', 'aCmd_log', 'SaveFormat', 'Structure With Time');

% Controller code (char vector for older MATLAB compatibility)
ctrlCode = sprintf(['function [aCmd, mode] = fcn(vE, d, vL, modePrev, aPrev, dt, vSet, Th, d0, Kv_free, Kd, Kv_rel, aMin, aMax, jMax, dDetectOn, dDetectOff, dEmergency)\n' ...
'%#codegen\n' ...
'mode = modePrev;\n' ...
'if modePrev == uint8(0)\n' ...
'    if d < dDetectOn\n' ...
'        mode = uint8(1);\n' ...
'    end\n' ...
'else\n' ...
'    if d > dDetectOff\n' ...
'        mode = uint8(0);\n' ...
'    end\n' ...
'end\n' ...
'if d < dEmergency\n' ...
'    aRaw = aMin;\n' ...
'else\n' ...
'    if mode == uint8(0)\n' ...
'        aRaw = Kv_free * (vSet - vE);\n' ...
'    else\n' ...
'        dRef = d0 + Th * vE;\n' ...
'        aRaw = Kd * (d - dRef) + Kv_rel * (vL - vE);\n' ...
'    end\n' ...
'end\n' ...
'if aRaw > aMax\n' ...
'    aSat = aMax;\n' ...
'elseif aRaw < aMin\n' ...
'    aSat = aMin;\n' ...
'else\n' ...
'    aSat = aRaw;\n' ...
'end\n' ...
'aHi = aPrev + jMax * dt;\n' ...
'aLo = aPrev - jMax * dt;\n' ...
'if aSat > aHi\n' ...
'    aCmd = aHi;\n' ...
'elseif aSat < aLo\n' ...
'    aCmd = aLo;\n' ...
'else\n' ...
'    aCmd = aSat;\n' ...
'end\n' ...
'if aCmd > aMax\n' ...
'    aCmd = aMax;\n' ...
'elseif aCmd < aMin\n' ...
'    aCmd = aMin;\n' ...
'end\n']);
set_param([modelName '/ACC_Controller'], 'Script', ctrlCode);

plantCode = sprintf(['function [vE_next, d_next] = fcn(vE, d, vL, aCmd, dt)\n' ...
'%#codegen\n' ...
'vE_next = vE + aCmd * dt;\n' ...
'if vE_next < 0\n' ...
'    vE_next = 0;\n' ...
'end\n' ...
'd_next = d + (vL - vE) * dt;\n' ...
'if d_next < 0\n' ...
'    d_next = 0;\n' ...
'end\n']);
set_param([modelName '/Plant_Update'], 'Script', plantCode);

% Wiring
add_line(modelName, 'vE_z1/1', 'ACC_Controller/1');
add_line(modelName, 'd_z1/1', 'ACC_Controller/2');
add_line(modelName, 'vL_FromWs/1', 'ACC_Controller/3');
add_line(modelName, 'mode_z1/1', 'ACC_Controller/4');
add_line(modelName, 'aPrev_z1/1', 'ACC_Controller/5');

for i = 1:numel(pNames)
    add_line(modelName, [pNames{i} '/1'], ['ACC_Controller/' num2str(i+5)]);
end

add_line(modelName, 'vE_z1/1', 'Plant_Update/1');
add_line(modelName, 'd_z1/1', 'Plant_Update/2');
add_line(modelName, 'vL_FromWs/1', 'Plant_Update/3');
add_line(modelName, 'ACC_Controller/1', 'Plant_Update/4');
add_line(modelName, 'dt/1', 'Plant_Update/5');

add_line(modelName, 'Plant_Update/1', 'vE_z1/1', 'autorouting', 'on');
add_line(modelName, 'Plant_Update/2', 'd_z1/1', 'autorouting', 'on');
add_line(modelName, 'ACC_Controller/2', 'mode_z1/1');
add_line(modelName, 'ACC_Controller/1', 'aPrev_z1/1');

add_line(modelName, 'vE_z1/1', 'ToWs_vE/1');
add_line(modelName, 'd_z1/1', 'ToWs_d/1');
add_line(modelName, 'ACC_Controller/1', 'ToWs_aCmd/1');

save_system(modelName, modelPath);
close_system(modelName);

fprintf('[02_make_model] created: %s\n', modelPath);
